author = "Ayush Biswas"

editor = "pycharm"

[code]
filename = '''{{#if (regex_is_match pattern="codeforces.com" on=url)}} {{#with (regex_captures
    pattern="(?:problemset/problem|contest)/(\\d+)(?:/problem)?/([A-Za-z0-9]+)"
    on=url) as |url_parts|}} {{#with (regex_captures
      pattern="^[A-Za-z0-9]+\\.\\s*(.+)$"
      on=../title) as |title_parts|}}
./src/{{url_parts._1}}-{{to_lower_case url_parts._2}}-{{to_kebab_case title_parts._1}}.py
{{/with}}
{{/with}}
{{/if}}
{{#if (regex_is_match pattern="atcoder.jp" on=url)}} {{#with (regex_captures
  pattern="contests/([^/]+)/tasks/([^_]+)_([a-z]+)"
  on=url) as |url_parts|}} {{#with (regex_captures
    pattern="^[A-Za-z0-9]+\\s*\\-\\s*(.+)$"
    on=../title) as |title_parts|}}
./src/{{url_parts._1}}-{{to_lower_case url_parts._3}}{{#if (to_kebab_case title_parts._1)}}-{{to_kebab_case title_parts._1}}{{/if}}.py
{{/with}}
{{/with}}
{{/if}}
{{#if (regex_is_match pattern="cses.fi" on=url)}}
{{#with (regex_captures
  pattern="problemset/task/(\\d+)/?$"
  on=url) as |url_parts|}}
./src/cses-{{url_parts._1}}-{{to_kebab_case ../title}}.py
{{/with}}
{{/if}}
'''
template = "./main.py"
modifier = """
{{#each lib_files}}

###### {{this.0}} #####
{{{this.1}}}
###### {{this.0}} #####

{{/each}}
###### main #####
{{{code}}}
###### main #####
"""
lib_check_regex = "from.*{{name}}"

[include]
_ = "./cpio/"

[toggle]
create_file = true
run_on_save = true
submit_on_ac = false
